/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
Traceback (most recent call last):
  File "/home/thussenot/.conda/envs/multinest/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/analysis.py", line 596, in main
    priors = create_prior_from_args(model_names, args)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/nmma/em/prior.py", line 77, in create_prior_from_args
    priors = bilby.gw.prior.PriorDict(args.prior)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 42, in __init__
    self.from_file(dictionary)
  File "/home/thussenot/.conda/envs/multinest/lib/python3.8/site-packages/bilby/core/prior/dict.py", line 149, in from_file
    with ioopen(filename, "r", encoding="unicode_escape") as f:
FileNotFoundError: [Errno 2] No such file or directory: './Bu2019lm_TrPi2018_GRB211211A.prior'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[25796,1],20]
  Exit code:    1
--------------------------------------------------------------------------
